# Created by react-native-pod
target 'hrsl' do
  # We uncomment because we like dynamic frameworks witn working with swift projects
  use_frameworks!
  # Add new pods below this line

  pod 'RNWifi', :path => '../node_modules/react-native-wifi-reborn'

  pod 'react-native-voice', :path => '../node_modules/react-native-voice'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-print', :path => '../node_modules/react-native-print'

  pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  
  target 'hrslTests' do
    inherit! :search_paths
    # Pods for testing
    # Add new pods below this line

    pod 'RNWifi', :path => '../node_modules/react-native-wifi-reborn'

    pod 'react-native-voice', :path => '../node_modules/react-native-voice'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'RNScreens', :path => '../node_modules/react-native-screens'

    pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    pod 'react-native-print', :path => '../node_modules/react-native-print'

    pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'

    pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  end
end
target 'hrsl-tvOS' do
  # We uncomment because we like dynamic frameworks witn working with swift projects
  use_frameworks!
  target 'hrsl-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
