export * from './consentimiento';
export * from './1 REGISTRO-INGRESO-EGRESO';
export * from './2 HOJA-FRONTAL';
export * from './3 NOTA-MEDICA';
export * from './5_1 NOTA-EVOLUCION-CLINICA';
export * from './5_3 NOTA-PREANESTESICA';
export * from './5_4 NOTA-POSTQUIRURGICA';
export * from './5_4 NOTA-PREQUIRURGICA';
export * from './5_4 NOTA-POSTQUIRURGICA';
export * from './7 INDICACIONES-MEDICAS';
export * from './logoCompleto';
export * from './logo';
